### PR TITLE
Associate parameter group with rds cluster

### PR DESCRIPTION
**Pull request by charles-nava**
## Ticket

Resolves [#385](https://github.com/navapbc/template-infra/issues/385)

## Changes

- Associate parameter group with db in db module
- Use data module to avoid circular dependency

## Testing

Terraform creates expected changes without deletion of resources (excluding automatic replacement of lambda package)
Screenshot 2023-09-19 at 10 45 47 AM
After application, expected parameter group is applied to cluster
Screenshot 2023-09-19 at 10 45 35 AM

### CODE REVIEW

**Comment by lorenyu** [comment]
@charles-nava for my own understanding and curiosity, could you share what some of the logs described by the parameter group look like?

e.g. maybe run database-migrations and then see if you can find logs for DROP/ALTER/CREATE?

**Comment by charles-nava** [comment]
Screenshot 2023-09-21 at 11 13 51 AM
[log-events-viewer-result.csv](https://github.com/navapbc/platform-test/files/12687618/log-events-viewer-result.csv)

@lorenyu Logs screenshot of ddl operations and 30 minutes of logs around migration run

**Comment by lorenyu** [comment]
@charles-nava i think you just shared the cloudwatch logs. i would expect based on the parameter group that there would be logs that log DDL statements. where are those logs stored? can you find those and share them? 

image

**Comment by charles-nava** [comment]
Those logs are in the [rds console under logs and events](https://us-east-1.console.aws.amazon.com/rds/home?region=us-east-1#database:id=app-dev-primary;is-cluster=false;tab=logs-and-events).
Taking a look at them however it looks like all of the recent logs are just errors
[postgresql.log.2023-09-21-1900.log](https://github.com/navapbc/platform-test/files/12691762/postgresql.log.2023-09-21-1900.log)

**Comment by charles-nava** [comment]
Reverting to draft while I figure out instance parameter groups in terraform as the cluster parameter group doesn't propagate

**Comment by lorenyu** [comment]
Thanks! Looking forward to your insights. I wonder if we need to restart the cluster or something like that.

**Comment by charles-nava** [comment]
Resolved as part of other [PR](https://github.com/navapbc/template-infra/pull/479)

**Pull request closed without merging**
